[project]
name = "mae5110"
version = "0.1.0"
description = "Course exercises for MAE 5110"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "ipython>=9.16.1",
    "matplotlib",
    "numpy",
    "ruff>=0.16.5",
]

[dependency-groups]
dev = [
    "pytest",
]

[tool.ruff.lint]

ignore = [
  "I001" # ignores import error things and vice versa
]
